### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Graflinger** [MicrosoftDocs/quantum-docs-pr.de-DE#1]
Unter der Überschrift Quantenalgorithmen im zweiten Absatz im ersten Satz ist ein Fehler: statt "Bits mit zwei möglichen Werten (1 oder 1)" sollte wohl "Bits mit zwei möglichen Werten (0 oder 1)" sein. Die englische Seite schaut richtig aus.

If english is better for you: Under the heading quantum algorithms in the second paragraph of the first sentence is an error: instead of "Bits mit zwei möglichen Werten (1 oder 1))" there should probably be "Bits mit zwei möglichen Werten (0 oder 1)".  The english site looks correct. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 16ca17e0-4031-faef-fc0d-b1406d3b778f
* Version Independent ID: d4b5084c-9c36-3321-5712-0ed8675d2427
* Content: [Was ist Quantencomputing? - Microsoft Quantum](https://docs.microsoft.com/de-de/quantum/overview/what-is-quantum-computing?view=qsharp-preview#feedback)
* Content Source: [articles/overview/what-is-quantum-computing.md](https://github.com/MicrosoftDocs/quantum-docs-pr.de-DE/blob/live-sxs/articles/overview/what-is-quantum-computing.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by srvbpigh** [comment]
Hello, @Graflinger
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hallo, @Graflinger,   

Vielen Dank für Ihr Feedback.  

unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/quantum/overview/what-is-quantum-computing?view=qsharp-preview#feedback.   

Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben.  

Mit freundlichen Grüßen  
das Microsoft DOCS International Team
