### ISSUE TITLE
German Version contains F# instead of Q#

### ISSUE THREAD

**Issue by thomasclaudiushuber** [MicrosoftDocs/quantum-docs-pr.de-DE#2]
The German version of this page contains translations with F# instead of Q#

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a3b73e69-99b5-c8a7-c20c-5b9b71f6c712
* Version Independent ID: 30736d0f-7226-ee59-7503-d0854104fac0
* Content: [Q#-Programmübersicht - Microsoft Quantum](https://docs.microsoft.com/de-de/quantum/techniques/file-structure#feedback)
* Content Source: [articles/techniques/file-structure.md](https://github.com/MicrosoftDocs/quantum-docs-pr.de-DE/blob/live-sxs/articles/techniques/file-structure.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **Christopher.Granade@microsoft.com**

**Comment by srvbpigh** [comment]
Hello, @thomasclaudiushuber
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @thomasclaudiushuber 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
